### PR TITLE
chore(all): implement lerna

### LINKED ISSUE #21: Enable individual installation of components
As part of the move to separate the components into a separate library, each component should now include all the required pieces to make a self-packaged component that can be installed individually in the use case where a user may not want to install the entire component suite.

The following will need to be accomplished for each component:
1. Create a `package.json` file containing the build script and package information
2. Create an `index.ts` file that is the entry point of the component when used individually

### Requirements
Aurelia UX Components should be able to be installed in one of two ways.

Option one, install the entire suite.
`npm install aurelia-ux-components --save`

Option two, install components individually.
`npm install aurelia-ux-components/component-name`

### Progress Tracker
This section will be updated as tasks are completed
#### Components
- [ ] Button
- [ ] Checkbox
- [ ] Chip Input
- [ ] Datepicker
- [ ] Form
- [ ] Icons
- [ ] Input
- [ ] Input Info
- [ ] Textarea
- [ ] List
- [ ] Tabs

### PR DESCRIPTION
**Pull request by ZHollingshead**
resolves #21

### Publish
```shell
lerna publish
```

### setup

```shell
lerna bootstrap
```

### Build
```shell
lerna run build
```

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Maybe we can remove the subfolders. Since each component is in its own package, we probably don't need the components-specific subfolder inside the src folder. Does that make sense?

**Comment by ZHollingshead** [comment]
Makes perfect sense, and I agree.

**Comment by ZHollingshead** [comment]
I made that change. I also fixed a handful of linting issues and tab spacing inconsistencies.

**Comment by ZHollingshead** [comment]
Superceeded by https://github.com/aurelia/ux/pull/98

**Pull request closed without merging**
